name: Post da manhã

on:
  schedule:
    - cron: '0 12 * * *'  # 9h BRT
  workflow_dispatch:

jobs:
  gerar_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instala dependências
        run: pip install openai

      - name: Gera post
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python gerar_post.py

      - name: Commit e push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add content/posts/
          git commit -m "☀️ Post da manhã" || echo "Nada novo para commit"
          git push
